### ISSUE TITLE
[error] Invaild PE.

### ISSUE THREAD

**Issue by GeorgePatsias** [D1rkMtr/FilelessRemotePE#1]
Hello,

Its more like a question other than an issue.

My payload is rejected during GetNTHeaders.
I tried signed and unsigned executables, and compared yours (mimi.exe) with my custom .exe for the NT headers and they are similar.
Yours works ok mine gets rejected.

Can you please help me identify the reason?

Thanks in advance.

**Comment by D1rkMtr** [comment]
It's probably the given URI is incorrect , that's why it didn't get the PE :
try in the GetPE function to print the content retrieved , if it get's printed as PE , probably i have to fix something , if it print HTML , u have to give a good URI

![image](https://user-images.githubusercontent.com/110354855/191704065-615ca510-3658-4aa3-bb5f-1059bd8495cd.png)

**Comment by GeorgePatsias** [comment]
![image](https://user-images.githubusercontent.com/7280295/191731142-f7095eb5-ef72-4ea4-8879-33a85c3dc1c9.png)

**Comment by D1rkMtr** [comment]
Unfortunately the current version , take URI in this form :   https://domain.com/PathToPE
i will improve it to accept this type   : [http]https://IPv4/PathToPE   sooner .
tnx for reporting the problem.
I will reply to this Issue , When the problem is solved

**Comment by GeorgePatsias** [comment]
Thank you very much!

**Comment by D1rkMtr** [comment]
I think i fix it , i will add other stuff , probably in the next hours it gonna be uploaded,  DM me on twitter so i can ping u when i update the project on github :

![image](https://user-images.githubusercontent.com/110354855/191818291-64b8f977-5e74-4c48-8953-4f2fb6596e97.png)

**Comment by D1rkMtr** [comment]
Noo Need , i UPDATED it , enjoy !!!

**Comment by GeorgePatsias** [comment]
Thank you very much ! 😄
